spring:
  cloud:
    stream:
      kafka:
        bindings:
          output:
            producer:
              configuration:
                value:
                  serializer: com.example.coin.upbit.support.kafka.CandleSerializer
